wandb_version: 1

region:
  desc: null
  value: Southeast Asia
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727824180.458721
    t:
      1:
      - 1
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 5
      13: darwin-arm64
