wandb_version: 1

client_number:
  desc: null
  value: '5'
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710065912.473367
    t:
      1:
      - 1
      - 3
      - 5
      - 6
      - 53
      - 55
      2:
      - 1
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
